name: generate contribution snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: generate snake svgs
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg?color_snake=#22D3EE,#0891B2&color_dots=#ebedf0,#99f6e4,#5eead4,#2dd4bf,#0f766e
            dist/github-snake-dark.svg?color_snake=#22D3EE,#0891B2&color_dots=#2d3343,#0f766e,#10b981,#34d399,#6ee7b7

      - name: push snake svgs to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
